---
title: "K Means Shiny App"
author: "Akhil Anand"
date: "2/9/2022"
output: html_document
---
```{r setiup, include=F}
library(shiny)
```

```{r}
devtools::install("kmeanspackage")
library(kmeanspackage)
```

### Final App
The app has the functions from the kmeans package now
```{r, final app, eval=F, echo=T}
ui <- fluidPage(
  
  # Put a titlePanel here
  titlePanel("k-means clustering"),
  
  sidebarLayout(
    # Sidebar. Put your inputs inside the sidebarPanel
    sidebarPanel(
      selectInput('xcol', 'X Variable', names(iris)),
      selectInput('ycol', 'Y Variable', names(iris),
                  selected=names(iris)[[2]]),
      numericInput('clusters', 'Cluster count', 3,
                   min = 1, max = 9)
    ),
    
    # Main panel. put your output plot here
    mainPanel(
      plotOutput('plot1')
    )
  )
)

server <- function(input, output, session) {
  
  selectedData <- reactive({
    iris[, c(input$xcol, input$ycol)]
  })
  
  clusters <- reactive({
    kmeans_function(selectedData(), input$clusters)
  })
  
  output$plot1 <- renderPlot({
    #palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
     #         "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))
    
    #par(mar = c(5.1, 4.1, 0, 1))
    #plot(selectedData(),
    #     col = clusters()$cluster,
    #     pch = 20, cex = 3)
    #points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
    plot_function(selectedData(), clusters())
  })
}

shinyApp(ui = ui, server = server)
```